name: KoiWild
main: com.koisv.koiwild.KoiWild
version: 0.1-SNAPSHOT
author: KeiKoi
website: "https://www.koisv.com"
api-version: 1.19
description: Wild Server Plugin
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20