name: KoiWild
main: com.koisv.koiwild.KoiWild
version: 0.24.1-SNAPSHOT
author: KeiKoi
website: "https://www.koisv.com"
api-version: '1.20'
description: Wild Server Plugin
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.21
#  - io.github.monun:kommand-core:3.1.6
commands:
  p:
    description: Patch Notes
    usage: /<command>
  pw:
    description: Write Patch
    permission: koiWild.writePatch
    usage: /<command> [u|d|<version>]

permissions:
  koiWild.writePatch:
    description: make patch
    default: op